### ISSUE TITLE
Do we want to keep interpreters on the same repo?

### ISSUE THREAD

**Issue by gabro** [buildo/metarpheus#23]
I've created https://github.com/buildo/metarpheus-swagger but I was thinking we could make a monorepo for core and interpreters, so that modifications to the morpheus specs could be done atomically.

As usual, we may have issues with the CI.

Thoughts, @utaal?

**Comment by utaal** [comment]
Some interpreters may end up containing internal names and knowledge. As long as they don't, they can definitely be added here.
As soon as pending PRs are merged, I'll make a commit moving the full tree into a subdir.

**Comment by gabro** [comment]
great, thanks

**Comment by utaal** [comment]
Done in 6ce7f02
