### ISSUE TITLE
npm package errors mysteriously

### ISSUE THREAD

**Issue by mmkal** [buildo/metarpheus#68]
Hi, I'm trying to use the npm package and got this error:

```cli
~/src/myproject$ node foo.js

/Users/myname/src/myproject/node_modules/metarpheus/index.js:162
function Bn(a,b){a:for(;;){if(Yh(b))return(new po).i(b.La());if(ki(b)){var c=b,c=null===c?q():(new r).b((new C).a(c.rc(),c.cb()));if(!c.n()){var e=c.p().ha(),c=c.p().o();if(Yh(e))return b=e.La(),a=p(function(a){return function(b){return Bn(a,b)}}(a)),e=li(),(new Xn).Rl(b,c.ja(a,e.e))}}if(bi(b)&&(c=b,c=null===c?q():(new r).b((new C).a(c.Ri(),c.ec())),!c.n())){b=c.p().o();continue a}throw(new O).b(b);}}
                  ^
Error
    at O.hN.cq (/Users/myname/src/myproject/node_modules/metarpheus/index.js:1130:206)
    at O.hN.ud (/Users/myname/src/myproject/node_modules/metarpheus/index.js:1130:446)
    at O.b (/Users/myname/src/myproject/node_modules/metarpheus/index.js:2176:320)
    at Bn (/Users/myname/src/myproject/node_modules/metarpheus/index.js:162:398)
    at /Users/myname/src/myproject/node_modules/metarpheus/index.js:150:309
    at TY.ba (/Users/myname/src/myproject/node_modules/metarpheus/index.js:1892:94)
    at /Users/myname/src/myproject/node_modules/metarpheus/index.js:2439:86
    at TY.ba (/Users/myname/src/myproject/node_modules/metarpheus/index.js:1892:94)
    at pd.d.jb (/Users/myname/src/myproject/node_modules/metarpheus/index.js:3958:145)
    at GM (/Users/myname/src/myproject/node_modules/metarpheus/index.js:2439:32)
~/src/myproject$
```

It's hard to tell what might be wrong because the js is minified without source maps.

`foo.js` just contains the example content here: https://www.npmjs.com/package/metarpheus with the path changed to my project root.

I might be trying to do the wrong thing though. I have an existing scala project and I want to convert some of the types to other languages. Is there an example project that does that, end-to-end? I can't find any docs. I'm not sure if I'm meant to be install sbt plugins, npm packages, or something else.

**Comment by gabro** [comment]
Hi @mmkal, error reporting could definitely be improved, I agree. This is sort of an internal tool, and we never needed it, but we would definitely accept PRs :)

As per your error, what Scala code are you trying to run this against?

To get a better error, you can try running the JVM version against it (`publishLocal` and then run the produced jar with `java -jar`), which should raise an exception in the point of the Scala code where this is actually breaking.

**Comment by gabro** [comment]
@mmkal in version 0.1.9 errors are now displayed in a human readable way.

If you try again you should be able to pinpoint where the error is.

**Comment by mmkal** [comment]
Nice, that worked. I may open another issue with the actual error! But I'll play around to see if I've misconfigured something first.

**Comment by gabro** [comment]
Sure! Let me know :)
